### ISSUE TITLE
CI: Provide "fuzz" for dinit!

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#90]
## Goal
Provide "fuzz" step for dinit in CI
## ToDo
- [x] Checkout dinit fuzzer backend (For debugging,improve...) (#91) 
- [x] Learn more about Fuzzer & LLVM's libfuzzer
- [x] Provide "fuzz" ci workflow(s) (#96)

### https://en.wikipedia.org/wiki/Fuzzing: Fuzzing, From Wikipedia, the free encyclopedia:
> In [programming](https://en.wikipedia.org/wiki/Computer_programming) and [software development](https://en.wikipedia.org/wiki/Software_development), fuzzing or fuzz testing is an automated [software testing](https://en.wikipedia.org/wiki/Software_testing) technique that involves providing invalid, unexpected, or [random data](https://en.wikipedia.org/wiki/Random_data) as inputs to a [computer program](https://en.wikipedia.org/wiki/Computer_program). The program is then monitored for exceptions such as [crashes](https://en.wikipedia.org/wiki/Crash_(computing)), failing built-in code [assertions](https://en.wikipedia.org/wiki/Assertion_(software_development)), or potential [memory leaks](https://en.wikipedia.org/wiki/Memory_leak). Typically, fuzzers are used to test programs that take structured inputs. This structure is specified, e.g., in a [file format](https://en.wikipedia.org/wiki/File_format) or [protocol](https://en.wikipedia.org/wiki/Communications_protocol) and distinguishes valid from invalid input. An effective fuzzer generates semi-valid inputs that are "valid enough" in that they are not directly rejected by the parser, but do create unexpected behaviors deeper in the program and are "invalid enough" to expose [corner cases](https://en.wikipedia.org/wiki/Corner_case) that have not been properly dealt with.
For the purpose of security, input that crosses a [trust boundary](https://en.wikipedia.org/wiki/Trust_boundary) is often the most useful.[[1]](https://en.wikipedia.org/wiki/Fuzzing#cite_note-neystadt-1) For example, it is more important to fuzz code that handles the upload of a file by any user than it is to fuzz the code that parses a configuration file that is accessible only to a privileged user.

### https://github.com/davmac314/dinit/blob/master/BUILD file description:
https://github.com/davmac314/dinit/blob/ececd169fbfac35035d0ddb6d7cc1d09ae1e5acf/BUILD#L116-L128

### LLVM's libfuzzer project page:
https://llvm.org/docs/LibFuzzer.html

**Comment by davmac314** [comment]
Note that it is not usual to run fuzzing as part of CI. Fuzzing is non-deterministic and time-intensive, it is best done as an occasional check (eg prior to release) when it can be run for several hours.

**Comment by mobin-2008** [comment]
I write a Github workflow. its not runned on every commits/PRs; its have `workflow_dispatch` for running it & use `ubuntu-latest`. Note: its not ready & need to refactoring/remove workarounds

**Comment by mobin-2008** [comment]
@davmac314 There's a problem: how to run fuzz for a certain amount of time (5 hours, 20 min...)? I tried to do this with `timeout`, but the `Return code` was always equal to `72`. That is, in fact, I have to do something so that if the fuzzer encounters `SIGTERM`, the program will be closed with return code `0`. Maybe it is not necessary, hmmm I don't know.

**Comment by mobin-2008** [comment]
I write a simple bash script for resolve this problem:
````
#!/usr/bin/env bash

## Run fuzzer for specife time

echo "./fuzz" > ./fuzz_temp_runner
echo 'echo ${?} > ./fuzz_temp_runner_return_code' >> ./fuzz_temp_runner
chmod +x ./fuzz_temp_runner && ./fuzz_temp_runner &
sleep ${1}
pkill -15 fuzz

if [ $? = 0 ] && [ $(cat ./fuzz_temp_runner_return_code) = 72 ]; then
    echo "Timeout reached out and killed fuzz process; pkill return 0: Done"
    echo "fuzz process return $(cat ./fuzz_temp_runner_return_code) because We send SIGTERM to fuzz process; fuzz return $(cat ./fuzz_temp_runner_return_code): Done"
    echo "Fuzzer runned for ${1} and everything is OK."
    echo "Exiting... WITH RETURN CODE: 0"
    exit 0
elif [ $? != 0 ] && [ $(cat ./fuzz_temp_runner_return_code) != 72 ]; then
    echo "Timeout reached out but pkill Fail to send SIGTERM to fuzz process; pkill return ${?}: FAIL!"
    echo "fuzz process return $(cat ./fuzz_temp_runner_return_code) but pkill fail to send SIGTERM to fuzz process; fuzz return $(cat ./fuzz_temp_runner_return_code): FAIL!"
    echo "Fuzzer runned for ${1} and something is BROKEN."
    echo "Checkout logs."
    echo "Exiting... WITH RETURN CODE: 1"
    exit 1
fi
````
looks good but need more refactoring/reviewing

**Comment by davmac314** [comment]
Use `-max_total_time`, `-timeout` is for an individual input. Check the libfuzzer docs.
